# Run during the 'gulp build' command
# Overrides _config.yml

# these are the required settings for jekyllized
# that can't live in _config.yml b/c that is what cloudcannon must use
source: .tmp/src
destination: .tmp/dist
exclude: ['assets']

# Hides your drafts and future posts
future: false
show_drafts: false
# Removes the upper limit for posts generated
limit_posts: 0

defaults:
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      class: "home"
      permalink: "/"
  -
    scope:
      path: "index.de.html"
    values:
      layout: "default"
      class: "home"
      permalink: "/"
      _hide_content: true
  -
    scope:
      path: "portfolio.html"
    values:
      layout: "default"
      class: "portfolio"
      permalink: "/portfolio/"
  -
    scope:
      path: "portfolio.de.html"
    values:
      layout: "default"
      class: "portfolio"
      permalink: "/portfolio/"
      _hide_content: true
  -
    scope:
      path: "about.html"
    values:
      layout: "default"
      class: "about"
      permalink: "/about/"
  -
    scope:
      path: "about.de.html"
    values:
      layout: "default"
      class: "about"
      permalink: "/about/"
      _hide_content: true
  -
    scope:
      path: "capabilities.html"
    values:
      layout: "default"
      class: "capabilities"
      permalink: "/capabilities/"
  -
    scope:
      path: "capabilities.de.html"
    values:
      layout: "default"
      class: "capabilities"
      permalink: "/capabilities/"
      _hide_content: true
  -
    scope:
      path: "careers.html"
    values:
      layout: "default"
      class: "careers"
      permalink: "/careers/"
  -
    scope:
      path: "careers.de.html"
    values:
      layout: "default"
      class: "careers"
      permalink: "/careers/"
      _hide_content: true
  -
    scope:
      path: "jobs.html"
    values:
      layout: "default"
      class: "jobs"
      permalink: "/careers/jobs/"
  -
    scope:
      path: "jobs.de.html"
    values:
      layout: "default"
      class: "jobs"
      permalink: "/careers/jobs/"
      _hide_content: true
  -
    scope:
      path: "internships.html"
    values:
      layout: "default"
      class: "internships"
      permalink: "/careers/internships/"
  -
    scope:
      path: "internships.de.html"
    values:
      layout: "default"
      class: "internships"
      permalink: "/careers/internships/"
      _hide_content: true
  -
    scope:
      path: ""
      type: "case_studies"
    values:
      layout: "casestudy"
      class: "casestudy"
  -
    scope:
      path: "clients.html"
    values:
      layout: "default"
      class: "clients"
      permalink: "/clients/"
  -
    scope:
      path: "clients.de.html"
    values:
      layout: "default"
      class: "clients"
      permalink: "/clients/"
      _hide_content: true
  -
    scope:
      path: "contact.html"
    values:
      layout: "default"
      class: "contact"
      permalink: "/contact/"
  -
    scope:
      path: "contact.de.html"
    values:
      layout: "default"
      class: "contact"
      permalink: "/contact/"
      _hide_content: true
  -
    scope:
      path: "press.html"
    values:
      layout: "default"
      class: "press"
      permalink: "/press/"
  -
    scope:
      path: "press.de.html"
    values:
      layout: "default"
      class: "press"
      permalink: "/press/"
      _hide_content: true
  -
    scope:
      path: ""
      type: "jobs"
    values:
      layout: "job"
      class: "job"
  -
    scope:
      path: ""
      type: "internships"
    values:
      layout: "job"
      class: "job"
  -
    scope:
      path: "cms.md"
    values:
      layout: "cms"
      permalink: "/cms/"
      _hide_content: true