# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Merritt Woodwork
description:
url: http://www.merrittwoodwork.com

# CloudCannon uses these:
source: src
destination: dist
exclude:

work-types:
  - superyacht
  - contemporary
  - traditional
  - transitional

job-locations:
  - california
  - florida
  - germany
  - new jersey
  - ohio
  - utah
  - wisconsin

job-types:
  - full time
  - part time



# Extending Jekyll
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
